### ISSUE TITLE
索引针对region的split处理出现问题

### ISSUE THREAD

**Issue by jcai** [ganshane/roar#6]
因为在postSplit之前，daughter region已经启动，所以导致索引会加载失败

**Comment by jcai** [comment]
@rultor please release,tag is`0.0.3`

**Comment by jcai** [comment]
@rultor please release,tag is`0.0.3`

**Comment by jcai** [comment]
@rultor 
release,tag is `0.0.3`

**Comment by jcai** [comment]
@rultor 
please release,tag is `0.0.3`

**Comment by jcai** [comment]
@rultor 
please release,tag is `0.0.4`

**Comment by jcai** [comment]
@yegor256 rultor offline?

**Comment by jcai** [comment]
@rultor 
please release,tag is `0.0.3`

**Comment by yegor256** [comment]
@jcai it's up and running now
